mc_shop_shopping_cart_manage_item_list:
    path:   /
    defaults: { _controller: McShopShoppingCartBundle:Item:list }

mc_shop_shopping_cart_manage_item_new:
    path:   /new
    defaults: { _controller: McShopShoppingCartBundle:Item:new }
