services:
    McShop\ShoppingCartBundle\Menu\ShoppingCartMenu:
        arguments:
            - '@router'
            - '@security.authorization_checker'
        tags:
            - { name: mc_shop_menu, alias: shopping_cart }
        public: true

    McShop\ShoppingCartBundle\Menu\Builder\ShoppingCartMenuBuilder:
        arguments:
            - '@translator'
        tags:
            - { name: mc_shop_menu.builder, alias: shopping_cart }
        public: true
