services:
    McShop\StaticPageBundle\Menu\PageMenu:
        arguments:
            - '@router'
            - '@security.authorization_checker'
            - '@doctrine'
        tags:
            - { name: mc_shop_menu, alias: page }
        public: true

    McShop\StaticPageBundle\Menu\Builder\PageMenuBuilder:
        arguments:
            - '@translator'
        tags:
            - { name: mc_shop_menu.builder, alias: page }
        public: true
