mc_shop_user_login:
    path:     /login
    defaults: { _controller: McShopUserBundle:Default:login }

mc_shop_user_logout:
    path:     /logout

mc_shop_user_registration:
    path:     /signup
    defaults:
        _controller: McShopUserBundle:Registration:register

mc_shop_user_registration_code_check:
    path:     /signup/code_check/{code}
    defaults:
        _controller: McShopUserBundle:Registration:codeCheck


mc_shop_user_registration_code:
    path:     /signup/code
    defaults:
        _controller: McShopUserBundle:Registration:code
