mc_shop_user_login:
    path:     /login
    defaults: { _controller: McShopUserBundle:Default:login }

mc_shop_user_logout:
    path:     /logout

mc_shop_user_registration:
    path:     /signup
    defaults:
        _controller: McShopUserBundle:Registration:register
