services:
    security.role_hierarchy:
        class: McShop\UserBundle\Services\RoleHierarchy
        arguments: [ '%security.role_hierarchy.roles%', '@doctrine' ]

    md5salted_encoder:
        class: McShop\UserBundle\Encoders\Md5PasswordEncoder

    mc_shop.user.helper:
        class: McShop\UserBundle\Services\Helper\UserHelper
        arguments:
            - '@doctrine'
            - '@security.password_encoder'
            - '@session'
            - '@security.token_storage'
        public: true

    mc_shop.user_email.helper:
        class: McShop\UserBundle\Services\Helper\UserEmailHelper
        arguments:
            - '@twig'
            - '@mailer'

    mc_shop.user.registration.code.handler:
        class: McShop\UserBundle\Services\CodeHandler\RegistrationHandler
        arguments:
            - '@doctrine'
            - '@mc_shop.user_email.helper'
            - '%mailer_from%'
            - '@translator'
            - '@session'
            - '@security.token_storage'

    mc_shop.user.recover.code.handler:
        class: McShop\UserBundle\Services\CodeHandler\RecoverHandler
        arguments:
            - '@doctrine'
            - '@mc_shop.user_email.helper'
            - '@translator'
            - '%mailer_from%'

    McShop\UserBundle\Menu\UserMenu:
        arguments:
            - '@router'
            - '@security.authorization_checker'
            - '@security.token_storage'
        tags:
            - { name: mc_shop_menu, alias: user }
        public: true

    McShop\UserBundle\Menu\Builder\UserMenuBuilder:
        arguments:
            - '@translator'
        tags:
            - { name: mc_shop_menu.builder, alias: user }
        public: true
