mc_shop_user:
    resource: "@McShopUserBundle/Resources/config/routing.yml"
    prefix:   /user

mc_shop_news:
    resource: "@McShopNewsBundle/Resources/config/routing.yml"
    prefix:   /news

mc_shop_static_page:
    resource: "@McShopStaticPageBundle/Resources/config/routing.yml"
    prefix:   /page

mc_shop_servers:
    resource: "@McShopServersBundle/Resources/config/routing.yml"
    prefix:   /server


mc_shop_finance_coupon:
    resource: "@McShopFinanceBundle/Resources/config/routing_coupon.yml"
    prefix:   /coupon
