# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    McShop\Core\:
        resource: '../../src/McShop/Core/*'
        # exclude directories || files (if service is unused, it will be removed anyway)
        exclude: '../../src/McShop/Core/{Controller, Form, Helper}'

    McShop\:
        resource: '../../src/McShop/*/Enum/*'
        public: true

    McShop\Core\Twig\Title:
        public: true

    Gedmo\SoftDeleteable\SoftDeleteableListener:
        tags:
            - { name: 'doctrine.event_subscriber' }
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]

    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]

    Gedmo\Tree\TreeListener:
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]

    mc_shop.access.decision_manager: '@security.access.decision_manager'
