# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.title:
        class: McShop\Twig\Title

    app.twig.title_extension:
        class: McShop\Twig\Extension\TitleExtension
        arguments:
            - '@app.title'
        tags:
            - { name: twig.extension, alias: title }
