services:
    McShop\MenuBundle\Service\MenuCollection: ~
    McShop\MenuBundle\Service\BuilderCollection: ~

    mc_shop.menu.base_menu:
        abstract: true
        arguments:
            - '@router'
            - '@security.authorization_checker'

    McShop\MenuBundle\Factory\MenuFactory:
        autowire: true
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    McShop\MenuBundle\Twig\MenuExtension:
        arguments:
            - '@McShop\MenuBundle\Factory\MenuFactory'
            - '@twig'
            - '@McShop\SettingBundle\Service\SettingHelper'
            - '@filesystem'
            - '%kernel.root_dir%'
        tags:
            - { name: twig.extension, alias: mc_shop_menu }
        public: true