services:
    MinecraftServerStatus\MinecraftServerStatus:
        public: false

    MinecraftRcon\Rcon:
        public: true

    McShop\ServersBundle\Services\ServerStatusUpdate:
        arguments:
            - '@doctrine'
            - '@MinecraftServerStatus\MinecraftServerStatus'
        public: true

    McShop\ServersBundle\Listener\ServerListener:
        tags:
            - { name: doctrine.event_listener, event: 'prePersist', method: 'prePersist'}
