services:
    _instanceof:
        McShop\ShopBundle\Interfaces\ProductHandlerInterface:
            tags: { name: "mc_shop.item_handler" }
            public: true

    McShop\ShopBundle\Factory\ProductHandlerFactory:
        public: true

    McShop\ShopBundle\ProductHandler\ShoppingCartProductHandler:
        autowire: true
        autoconfigure: true

    McShop\ShopBundle\Form\ItemType:
        autowire: true
        autoconfigure: true
