services:
    McShop\SettingBundle\Service\SettingHelper:
        arguments: [ "@doctrine" ]
        public: true

    McShop\SettingBundle\Twig\SettingExtension:
        arguments: [ '@McShop\SettingBundle\Service\SettingHelper' ]
        tags: [{ name: twig.extension, alias: setting }]
