services:
    McShop\SettingBundle\Service\SettingHelper:
        arguments: [ "@doctrine" ]
        public: true

    mc_shop.setting.helper: '@McShop\SettingBundle\Service\SettingHelper'

    mc_shop.setting.twig:
        class: McShop\SettingBundle\Twig\SettingExtension
        arguments: [ '@McShop\SettingBundle\Service\SettingHelper' ]
        tags: [{ name: twig.extension, alias: setting }]
